// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restaurant.proto

package restaurant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request message for creating a new Restaurant
type RestaurantRequest struct {
	RestaurantId          int32                            `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	RestaurantName        string                           `protobuf:"bytes,2,opt,name=restaurant_name,json=restaurantName,proto3" json:"restaurant_name,omitempty"`
	RestaurantUrl         string                           `protobuf:"bytes,3,opt,name=restaurant_url,json=restaurantUrl,proto3" json:"restaurant_url,omitempty"`
	RestaurantDescription string                           `protobuf:"bytes,4,opt,name=restaurant_description,json=restaurantDescription,proto3" json:"restaurant_description,omitempty"`
	RestaurantAddress     string                           `protobuf:"bytes,5,opt,name=restaurant_address,json=restaurantAddress,proto3" json:"restaurant_address,omitempty"`
	RestaurantPhone       string                           `protobuf:"bytes,6,opt,name=restaurant_phone,json=restaurantPhone,proto3" json:"restaurant_phone,omitempty"`
	RestaurantLocation    string                           `protobuf:"bytes,7,opt,name=restaurant_location,json=restaurantLocation,proto3" json:"restaurant_location,omitempty"`
	RestaurantImage       string                           `protobuf:"bytes,8,opt,name=restaurant_image,json=restaurantImage,proto3" json:"restaurant_image,omitempty"`
	Operationals          []*RestaurantRequest_Operational `protobuf:"bytes,9,rep,name=operationals,proto3" json:"operationals,omitempty"`
	Cuisines              []*RestaurantRequest_Cuisine     `protobuf:"bytes,10,rep,name=cuisines,proto3" json:"cuisines,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                         `json:"-"`
	XXX_unrecognized      []byte                           `json:"-"`
	XXX_sizecache         int32                            `json:"-"`
}

func (m *RestaurantRequest) Reset()         { *m = RestaurantRequest{} }
func (m *RestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*RestaurantRequest) ProtoMessage()    {}
func (*RestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{0}
}

func (m *RestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantRequest.Unmarshal(m, b)
}
func (m *RestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantRequest.Marshal(b, m, deterministic)
}
func (m *RestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantRequest.Merge(m, src)
}
func (m *RestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_RestaurantRequest.Size(m)
}
func (m *RestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantRequest proto.InternalMessageInfo

func (m *RestaurantRequest) GetRestaurantId() int32 {
	if m != nil {
		return m.RestaurantId
	}
	return 0
}

func (m *RestaurantRequest) GetRestaurantName() string {
	if m != nil {
		return m.RestaurantName
	}
	return ""
}

func (m *RestaurantRequest) GetRestaurantUrl() string {
	if m != nil {
		return m.RestaurantUrl
	}
	return ""
}

func (m *RestaurantRequest) GetRestaurantDescription() string {
	if m != nil {
		return m.RestaurantDescription
	}
	return ""
}

func (m *RestaurantRequest) GetRestaurantAddress() string {
	if m != nil {
		return m.RestaurantAddress
	}
	return ""
}

func (m *RestaurantRequest) GetRestaurantPhone() string {
	if m != nil {
		return m.RestaurantPhone
	}
	return ""
}

func (m *RestaurantRequest) GetRestaurantLocation() string {
	if m != nil {
		return m.RestaurantLocation
	}
	return ""
}

func (m *RestaurantRequest) GetRestaurantImage() string {
	if m != nil {
		return m.RestaurantImage
	}
	return ""
}

func (m *RestaurantRequest) GetOperationals() []*RestaurantRequest_Operational {
	if m != nil {
		return m.Operationals
	}
	return nil
}

func (m *RestaurantRequest) GetCuisines() []*RestaurantRequest_Cuisine {
	if m != nil {
		return m.Cuisines
	}
	return nil
}

type RestaurantRequest_Operational struct {
	OperationalId         int32    `protobuf:"varint,1,opt,name=operational_id,json=operationalId,proto3" json:"operational_id,omitempty"`
	OperationalDay        string   `protobuf:"bytes,2,opt,name=operational_day,json=operationalDay,proto3" json:"operational_day,omitempty"`
	OperationalOpenHour   string   `protobuf:"bytes,3,opt,name=operational_open_hour,json=operationalOpenHour,proto3" json:"operational_open_hour,omitempty"`
	OperationalClosedHour string   `protobuf:"bytes,4,opt,name=operational_closed_hour,json=operationalClosedHour,proto3" json:"operational_closed_hour,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *RestaurantRequest_Operational) Reset()         { *m = RestaurantRequest_Operational{} }
func (m *RestaurantRequest_Operational) String() string { return proto.CompactTextString(m) }
func (*RestaurantRequest_Operational) ProtoMessage()    {}
func (*RestaurantRequest_Operational) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{0, 0}
}

func (m *RestaurantRequest_Operational) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantRequest_Operational.Unmarshal(m, b)
}
func (m *RestaurantRequest_Operational) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantRequest_Operational.Marshal(b, m, deterministic)
}
func (m *RestaurantRequest_Operational) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantRequest_Operational.Merge(m, src)
}
func (m *RestaurantRequest_Operational) XXX_Size() int {
	return xxx_messageInfo_RestaurantRequest_Operational.Size(m)
}
func (m *RestaurantRequest_Operational) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantRequest_Operational.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantRequest_Operational proto.InternalMessageInfo

func (m *RestaurantRequest_Operational) GetOperationalId() int32 {
	if m != nil {
		return m.OperationalId
	}
	return 0
}

func (m *RestaurantRequest_Operational) GetOperationalDay() string {
	if m != nil {
		return m.OperationalDay
	}
	return ""
}

func (m *RestaurantRequest_Operational) GetOperationalOpenHour() string {
	if m != nil {
		return m.OperationalOpenHour
	}
	return ""
}

func (m *RestaurantRequest_Operational) GetOperationalClosedHour() string {
	if m != nil {
		return m.OperationalClosedHour
	}
	return ""
}

type RestaurantRequest_Cuisine struct {
	CuisineId            int32    `protobuf:"varint,1,opt,name=cuisine_id,json=cuisineId,proto3" json:"cuisine_id,omitempty"`
	CuisineName          string   `protobuf:"bytes,2,opt,name=cuisine_name,json=cuisineName,proto3" json:"cuisine_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantRequest_Cuisine) Reset()         { *m = RestaurantRequest_Cuisine{} }
func (m *RestaurantRequest_Cuisine) String() string { return proto.CompactTextString(m) }
func (*RestaurantRequest_Cuisine) ProtoMessage()    {}
func (*RestaurantRequest_Cuisine) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{0, 1}
}

func (m *RestaurantRequest_Cuisine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantRequest_Cuisine.Unmarshal(m, b)
}
func (m *RestaurantRequest_Cuisine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantRequest_Cuisine.Marshal(b, m, deterministic)
}
func (m *RestaurantRequest_Cuisine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantRequest_Cuisine.Merge(m, src)
}
func (m *RestaurantRequest_Cuisine) XXX_Size() int {
	return xxx_messageInfo_RestaurantRequest_Cuisine.Size(m)
}
func (m *RestaurantRequest_Cuisine) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantRequest_Cuisine.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantRequest_Cuisine proto.InternalMessageInfo

func (m *RestaurantRequest_Cuisine) GetCuisineId() int32 {
	if m != nil {
		return m.CuisineId
	}
	return 0
}

func (m *RestaurantRequest_Cuisine) GetCuisineName() string {
	if m != nil {
		return m.CuisineName
	}
	return ""
}

type RestaurantResponse struct {
	RestaurantId         int32    `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantResponse) Reset()         { *m = RestaurantResponse{} }
func (m *RestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*RestaurantResponse) ProtoMessage()    {}
func (*RestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{1}
}

func (m *RestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantResponse.Unmarshal(m, b)
}
func (m *RestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantResponse.Marshal(b, m, deterministic)
}
func (m *RestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantResponse.Merge(m, src)
}
func (m *RestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_RestaurantResponse.Size(m)
}
func (m *RestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantResponse proto.InternalMessageInfo

func (m *RestaurantResponse) GetRestaurantId() int32 {
	if m != nil {
		return m.RestaurantId
	}
	return 0
}

func (m *RestaurantResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RestaurantFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantFilter) Reset()         { *m = RestaurantFilter{} }
func (m *RestaurantFilter) String() string { return proto.CompactTextString(m) }
func (*RestaurantFilter) ProtoMessage()    {}
func (*RestaurantFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{2}
}

func (m *RestaurantFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantFilter.Unmarshal(m, b)
}
func (m *RestaurantFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantFilter.Marshal(b, m, deterministic)
}
func (m *RestaurantFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantFilter.Merge(m, src)
}
func (m *RestaurantFilter) XXX_Size() int {
	return xxx_messageInfo_RestaurantFilter.Size(m)
}
func (m *RestaurantFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantFilter.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantFilter proto.InternalMessageInfo

func (m *RestaurantFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*RestaurantRequest)(nil), "restaurant.RestaurantRequest")
	proto.RegisterType((*RestaurantRequest_Operational)(nil), "restaurant.RestaurantRequest.Operational")
	proto.RegisterType((*RestaurantRequest_Cuisine)(nil), "restaurant.RestaurantRequest.Cuisine")
	proto.RegisterType((*RestaurantResponse)(nil), "restaurant.RestaurantResponse")
	proto.RegisterType((*RestaurantFilter)(nil), "restaurant.RestaurantFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestaurantClient is the client API for Restaurant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestaurantClient interface {
	// Get all Restaurant with filter - A server-to-client streaming RPC.
	GetRestaurants(ctx context.Context, in *RestaurantFilter, opts ...grpc.CallOption) (Restaurant_GetRestaurantsClient, error)
	// Create a new Restaurant - A simple RPC
	CreateRestaurant(ctx context.Context, in *RestaurantRequest, opts ...grpc.CallOption) (*RestaurantResponse, error)
}

type restaurantClient struct {
	cc *grpc.ClientConn
}

func NewRestaurantClient(cc *grpc.ClientConn) RestaurantClient {
	return &restaurantClient{cc}
}

func (c *restaurantClient) GetRestaurants(ctx context.Context, in *RestaurantFilter, opts ...grpc.CallOption) (Restaurant_GetRestaurantsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Restaurant_serviceDesc.Streams[0], "/restaurant.Restaurant/GetRestaurants", opts...)
	if err != nil {
		return nil, err
	}
	x := &restaurantGetRestaurantsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Restaurant_GetRestaurantsClient interface {
	Recv() (*RestaurantRequest, error)
	grpc.ClientStream
}

type restaurantGetRestaurantsClient struct {
	grpc.ClientStream
}

func (x *restaurantGetRestaurantsClient) Recv() (*RestaurantRequest, error) {
	m := new(RestaurantRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *restaurantClient) CreateRestaurant(ctx context.Context, in *RestaurantRequest, opts ...grpc.CallOption) (*RestaurantResponse, error) {
	out := new(RestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant.Restaurant/CreateRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantServer is the server API for Restaurant service.
type RestaurantServer interface {
	// Get all Restaurant with filter - A server-to-client streaming RPC.
	GetRestaurants(*RestaurantFilter, Restaurant_GetRestaurantsServer) error
	// Create a new Restaurant - A simple RPC
	CreateRestaurant(context.Context, *RestaurantRequest) (*RestaurantResponse, error)
}

func RegisterRestaurantServer(s *grpc.Server, srv RestaurantServer) {
	s.RegisterService(&_Restaurant_serviceDesc, srv)
}

func _Restaurant_GetRestaurants_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestaurantFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RestaurantServer).GetRestaurants(m, &restaurantGetRestaurantsServer{stream})
}

type Restaurant_GetRestaurantsServer interface {
	Send(*RestaurantRequest) error
	grpc.ServerStream
}

type restaurantGetRestaurantsServer struct {
	grpc.ServerStream
}

func (x *restaurantGetRestaurantsServer) Send(m *RestaurantRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Restaurant_CreateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServer).CreateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant.Restaurant/CreateRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServer).CreateRestaurant(ctx, req.(*RestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Restaurant_serviceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant.Restaurant",
	HandlerType: (*RestaurantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRestaurant",
			Handler:    _Restaurant_CreateRestaurant_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRestaurants",
			Handler:       _Restaurant_GetRestaurants_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "restaurant.proto",
}

func init() { proto.RegisterFile("restaurant.proto", fileDescriptor_9528536a6390faa1) }

var fileDescriptor_9528536a6390faa1 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x29, 0xcd, 0x65, 0x92, 0x96, 0x74, 0xaa, 0xc2, 0x2a, 0xa2, 0x28, 0x18, 0x55, 0xa4,
	0x12, 0x04, 0x14, 0x04, 0xef, 0x55, 0x2a, 0x20, 0xe2, 0x52, 0x70, 0xc5, 0x73, 0xb4, 0xd8, 0x23,
	0x6a, 0xe1, 0x78, 0xcd, 0xae, 0x2d, 0x94, 0xbf, 0xe1, 0x23, 0xf8, 0x09, 0xfe, 0x0a, 0x79, 0x6d,
	0x77, 0x87, 0x00, 0x51, 0x1f, 0xf7, 0xdc, 0x26, 0xbb, 0x73, 0x62, 0x18, 0x68, 0x32, 0xb9, 0x2c,
	0xb4, 0x4c, 0xf3, 0x49, 0xa6, 0x55, 0xae, 0x10, 0x1c, 0xe2, 0xff, 0x68, 0xc1, 0x7e, 0x70, 0x75,
	0x0c, 0xe8, 0x5b, 0x41, 0x26, 0xc7, 0x07, 0xb0, 0xeb, 0x34, 0x8b, 0x38, 0x12, 0xde, 0xc8, 0x1b,
	0xef, 0x04, 0x7d, 0x07, 0xce, 0x23, 0x7c, 0x08, 0xb7, 0x98, 0x28, 0x95, 0x4b, 0x12, 0x37, 0x46,
	0xde, 0xb8, 0x1b, 0xec, 0x39, 0xf8, 0xbd, 0x5c, 0x12, 0x1e, 0x03, 0x43, 0x16, 0x85, 0x4e, 0xc4,
	0xb6, 0xd5, 0xb1, 0x19, 0x9f, 0x74, 0x82, 0xcf, 0xe1, 0x36, 0x93, 0x45, 0x64, 0x42, 0x1d, 0x67,
	0x79, 0xac, 0x52, 0x71, 0xd3, 0xca, 0x0f, 0x1d, 0x7b, 0xe6, 0x48, 0x7c, 0x0c, 0xc8, 0x6c, 0x32,
	0x8a, 0x34, 0x19, 0x23, 0x76, 0xac, 0x65, 0xdf, 0x31, 0xa7, 0x15, 0x81, 0x27, 0xfc, 0x41, 0x16,
	0xd9, 0xa5, 0x4a, 0x49, 0xb4, 0xac, 0x98, 0xdd, 0xe6, 0x43, 0x09, 0xe3, 0x13, 0x38, 0x60, 0xd2,
	0x44, 0x85, 0xd2, 0xfe, 0x9a, 0xb6, 0x55, 0xb3, 0xa1, 0x6f, 0x6b, 0x66, 0x2d, 0x3b, 0x5e, 0xca,
	0x2f, 0x24, 0x3a, 0xeb, 0xd9, 0xf3, 0x12, 0xc6, 0x77, 0xd0, 0x57, 0x19, 0x69, 0xeb, 0x93, 0x89,
	0x11, 0xdd, 0xd1, 0xf6, 0xb8, 0x37, 0x3d, 0x99, 0xb0, 0x65, 0xfd, 0xb5, 0x96, 0xc9, 0xb9, 0x73,
	0x04, 0x7f, 0xd8, 0xf1, 0x14, 0x3a, 0x61, 0x11, 0x9b, 0x38, 0x25, 0x23, 0xc0, 0x46, 0x1d, 0x6f,
	0x8e, 0x9a, 0x55, 0xea, 0xe0, 0xca, 0x36, 0xfc, 0xe5, 0x41, 0x8f, 0x0d, 0x28, 0xb7, 0xc6, 0x46,
	0xb8, 0x12, 0xec, 0x32, 0xb4, 0x6a, 0x01, 0x97, 0x45, 0x72, 0xd5, 0xb4, 0x80, 0xc1, 0x67, 0x72,
	0x85, 0x53, 0x38, 0xe4, 0x42, 0x95, 0x51, 0xba, 0xb8, 0x54, 0x85, 0xae, 0xcb, 0x70, 0xc0, 0xc8,
	0xf3, 0x8c, 0xd2, 0xd7, 0xaa, 0xd0, 0xf8, 0x02, 0xee, 0x70, 0x4f, 0x98, 0x28, 0x43, 0x51, 0xe5,
	0xaa, 0x3b, 0xc1, 0xe8, 0x99, 0x65, 0x4b, 0xdf, 0xf0, 0x0d, 0xb4, 0xeb, 0x0b, 0xe2, 0x11, 0x40,
	0x7d, 0x45, 0x77, 0x85, 0x6e, 0x8d, 0xcc, 0x23, 0xbc, 0x0f, 0xfd, 0x86, 0x66, 0x0d, 0xee, 0xd5,
	0x58, 0x59, 0x5f, 0xff, 0x02, 0x90, 0xbf, 0x9f, 0xc9, 0x54, 0x6a, 0xe8, 0x7a, 0x7f, 0x11, 0x01,
	0x6d, 0x53, 0x84, 0x61, 0x59, 0xc8, 0x32, 0xb8, 0x13, 0x34, 0x47, 0xff, 0x11, 0x0c, 0x5c, 0xe8,
	0xcb, 0x38, 0xc9, 0x49, 0x97, 0xea, 0xaf, 0xb4, 0xfa, 0xae, 0x74, 0x15, 0xd6, 0x0d, 0x9a, 0xe3,
	0xf4, 0xa7, 0x07, 0xe0, 0xe4, 0xf8, 0x11, 0xf6, 0x5e, 0x51, 0xee, 0x00, 0x83, 0x77, 0xff, 0xbd,
	0xed, 0x2a, 0x78, 0x78, 0xb4, 0xb1, 0x0b, 0xfe, 0xd6, 0x53, 0x0f, 0x2f, 0x60, 0x30, 0xd3, 0x24,
	0x73, 0x62, 0x63, 0x36, 0xdb, 0x86, 0xf7, 0xfe, 0x47, 0x57, 0x2f, 0xe4, 0x6f, 0x7d, 0x6e, 0xd9,
	0xef, 0xcd, 0xb3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x5e, 0xfc, 0xe4, 0x83, 0x04, 0x00,
	0x00,
}
